<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductDimensionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product_dimension')->insert([
            [
                'sku_number' => 'KS946RUR',
                'product_description' => 'Ballpoint pen 0.5 mm',
                'brand_name' => 'Snowman',
                'subcategory_name' => 'Ballpoint pen',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS945RUR',
                'product_description' => 'Ballpoint pen 0.2 mm',
                'brand_name' => 'Snowman',
                'subcategory_name' => 'Ballpoint pen',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS944RUR',
                'product_description' => 'Pencil HB',
                'brand_name' => 'Faber-Castel II',
                'subcategory_name' => 'Pencil',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS943RUR',
                'product_description' => 'Pencil 2B',
                'brand_name' => 'Faber-Castel II',
                'subcategory_name' => 'Pencil',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS942RUR',
                'product_description' => 'Spidol pack 12-color',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Spidol pack',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS941RUR',
                'product_description' => 'Spidol pack 6-color',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Spidol pack',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS940RUR',
                'product_description' => 'Highlighter XS',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Highlighter',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS939RUR',
                'product_description' => 'Highlighter XSS',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Highlighter',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS938RUR',
                'product_description' => 'Crayon pack 30-color',
                'brand_name' => 'Faber-Castel II',
                'subcategory_name' => 'Crayon pack',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS937RUR',
                'product_description' => 'Crayon pack 60-color',
                'brand_name' => 'Faber-Castel II',
                'subcategory_name' => 'Crayon pack',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS936RUR',
                'product_description' => 'Coloring pencil pack 30-color',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Coloring pencil pack',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS935RUR',
                'product_description' => 'Coloring pencil pack 60-color',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Coloring pencil pack',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS934RUR',
                'product_description' => 'Brush pen M',
                'brand_name' => 'Sakura',
                'subcategory_name' => 'Brush pen',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS933RUR',
                'product_description' => 'Brush pen L',
                'brand_name' => 'Sakura',
                'subcategory_name' => 'Brush pen',
                'category_name' => 'Writing tools',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS932RUR',
                'product_description' => 'Notebook A5',
                'brand_name' => 'Sinar Dunia (SiDU)',
                'subcategory_name' => 'Notebook',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS931RUR',
                'product_description' => 'Binder A4',
                'brand_name' => 'Kiky',
                'subcategory_name' => 'Binder',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS930RUR',
                'product_description' => 'Binder A5',
                'brand_name' => 'Kiky',
                'subcategory_name' => 'Binder',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS929RUR',
                'product_description' => 'Post-it original',
                'brand_name' => 'Post-it',
                'subcategory_name' => 'Loose Leaf Paper',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS928RUR',
                'product_description' => 'Memo pad A4',
                'brand_name' => 'Kiky',
                'subcategory_name' => 'Memo Pad',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS927RUR',
                'product_description' => 'Kertas HVS (A4,F4,A3)',
                'brand_name' => 'SiDU',
                'subcategory_name' => 'Printing Paper',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS926RUR',
                'product_description' => 'Photo paper A4',
                'brand_name' => 'Epson',
                'subcategory_name' => 'Photo Paper',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS925RUR',
                'product_description' => 'Art paper A4',
                'brand_name' => 'ArtCarton',
                'subcategory_name' => 'Art Paper',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS924RUR',
                'product_description' => 'Tracing paper A4',
                'brand_name' => 'Kokuyo',
                'subcategory_name' => 'Tracing Paper',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS923RUR',
                'product_description' => 'Wall calender festive',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Wall Calendar',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS922RUR',
                'product_description' => 'Planner original',
                'brand_name' => 'Kokuyo',
                'subcategory_name' => 'Planner',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS921RUR',
                'product_description' => 'Agenda A5',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Agenda',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS920RUR',
                'product_description' => 'Diary plaid A5',
                'brand_name' => 'Campus',
                'subcategory_name' => 'Diary',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'KS919RUR',
                'product_description' => 'Diary checkered A5',
                'brand_name' => 'Campus',
                'subcategory_name' => 'Diary',
                'category_name' => 'Papers',
                'department_name' => 'Stationery',
            ],
            [
                'sku_number' => 'VG384ZYU',
                'product_description' => 'Clear holder 10-pocket',
                'brand_name' => 'Eagle',
                'subcategory_name' => 'Clear Holder',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG385ZYU',
                'product_description' => 'Clear holder 20-pocket',
                'brand_name' => 'Eagle',
                'subcategory_name' => 'Clear Holder',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG386ZYU',
                'product_description' => 'Clear holder 30-pocket',
                'brand_name' => 'Eagle',
                'subcategory_name' => 'Clear Holder',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG387ZYU',
                'product_description' => 'Paper clip 50-pack',
                'brand_name' => 'Monotaro',
                'subcategory_name' => 'Paper clip',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG388ZYU',
                'product_description' => 'Paper clip 200-pack',
                'brand_name' => 'Monotaro',
                'subcategory_name' => 'Paper clip',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG389ZYU',
                'product_description' => 'Box file PVC',
                'brand_name' => 'Bantex',
                'subcategory_name' => 'Box file',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG390ZYU',
                'product_description' => 'Box file PVC Plus',
                'brand_name' => 'Bantex',
                'subcategory_name' => 'Box file',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG391ZYU',
                'product_description' => 'Box file clear',
                'brand_name' => 'Monotaro',
                'subcategory_name' => 'Box file',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG392ZYU',
                'product_description' => 'Stapler HD-10',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Stapler',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG393ZYU',
                'product_description' => 'Stapler HD-50',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Stapler',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG394ZYU',
                'product_description' => 'Stapler heavy duty',
                'brand_name' => 'Sakura',
                'subcategory_name' => 'Stapler',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG395ZYU',
                'product_description' => 'Paper puncher basic',
                'brand_name' => 'Carla Craft',
                'subcategory_name' => 'Paper puncher',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG396ZYU',
                'product_description' => 'Paper puncher extreme',
                'brand_name' => 'Carla Craft',
                'subcategory_name' => 'Paper puncher',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG397ZYU',
                'product_description' => 'Dater stamp',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Stamp',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG398ZYU',
                'product_description' => 'Flash stamp',
                'brand_name' => 'USPS',
                'subcategory_name' => 'Stamp',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG399ZYU',
                'product_description' => 'Scissors',
                'brand_name' => 'Kenko',
                'subcategory_name' => 'Scissors',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG400ZYU',
                'product_description' => 'Cutter Knife',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Cutter',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG401ZYU',
                'product_description' => 'Glue stick',
                'brand_name' => 'UHU',
                'subcategory_name' => 'Glue',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG402ZYU',
                'product_description' => 'Liquid glue',
                'brand_name' => 'Fox',
                'subcategory_name' => 'Glue',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG403ZYU',
                'product_description' => 'Glue Gun + Stick',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Glue',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG404ZYU',
                'product_description' => 'Ruler plastic',
                'brand_name' => 'Joyko',
                'subcategory_name' => 'Glue',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
            [
                'sku_number' => 'VG405ZYU',
                'product_description' => 'Ruler metal',
                'brand_name' => 'Butterfly',
                'subcategory_name' => 'Measuring tools',
                'category_name' => 'Office',
                'department_name' => 'Office supplies',
            ],
        ]);
    }
}



